### ISSUE TITLE
LaTex in Fragen wird nicht dargestellt

### ISSUE THREAD

**Issue by mba** [TUM-MZ/moodle_mod-quizinvideo#10]
Filter ist aktiviert.
Latex wird im Fragenpool angezeigt, aber nicht in Quiz-in-Video.

Getestet mit:
Win8
Firefox
![tex_nicht_angezeigt](https://cloud.githubusercontent.com/assets/86684/10477307/742e9956-7255-11e5-8544-2760d6998381.png)

**Comment by abuzakaria** [comment]
solved in ed2dd5e363683e5f18f11e158d250f9ad962ab7f
