### ISSUE TITLE
Plugin-Übersicht: Variablen von Quiz-in-Video werden nicht korrekt angezeigt

### ISSUE THREAD

**Issue by mba** [TUM-MZ/moodle_mod-quizinvideo#13]
Die Übersicht wird unter "Einstellungen - Webadministration - Plugins - Plugin-Übersicht" angezeigt.
Alle Variablen unter Quiz-in-Video werden ohne Übersetzung (bzw. ohne irgendeine Sprache) dargestellt.

![tumtraining-administration-plugins-plugin-ubersicht](https://cloud.githubusercontent.com/assets/86684/13285586/c51b224e-dafb-11e5-996a-0454b31252e7.png)

**Comment by alendit** [comment]
Doesn't seem to be a problem anymore.
