### ISSUE TITLE
Quizinvideo funktioniert nicht in Moodle 3.1

### ISSUE THREAD

**Issue by scouli** [TUM-MZ/moodle_mod-quizinvideo#20]
Hallo,
ich wollte quizinvideo auf unserem Moodle Testserver testen (Version 3.1). Nach dem ich den Quiz (mit der URL eines Youtubevideos) angelegt habe, wollte ich ihn testen, leider bekomme ich eine Fehlermeldung (siehe Screenshot). Habe ich etwas falsch gemacht?
![screenshot](https://cloud.githubusercontent.com/assets/21237316/17970211/e76df4d8-6ad5-11e6-817f-b474d5867f4a.jpg)

**Comment by alendit** [comment]
Hi,
kannst du den youtube-Link schicken, den du verwendet hast?
VG

**Comment by scouli** [comment]
Hallo,

als ich heute den Quizinvideo angeklickt habe sah ich einen Vorschau des Videos. Es lässt sich aber nicht abspielen (Screenshot). Hier ist den Link des Videos: https://www.youtube.com/watch?v=9clOnGeB3kU.

Gruß
Souleymane
![screenshot](https://cloud.githubusercontent.com/assets/21237316/17995569/1cd17f4a-6b63-11e6-9192-ba0fbefd1923.jpg)

**Comment by alendit** [comment]
Hallo,

wir haben jetzt seit neustem auf 3.1 Produktiv im Einsatz und das Video funktioniert bei uns ganz gut.

![qiv](https://cloud.githubusercontent.com/assets/81117/19112974/e18b2778-8b07-11e6-9d92-07b56e235719.png)

Manchmal zickt youtube aber, und man muss die Seite neuladen, damit das Video kommt. Wir schauen gerade, ob mal das eleganter lösen könnte. 

Ich schlisse den Ticket erstmal.
