### ISSUE TITLE
"Frage hinzufügen" funktioniert nicht

### ISSUE THREAD

**Issue by merxim** [TUM-MZ/moodle_mod-quizinvideo#22]
Beim Quiz-in-Video bearbeiten:
Wenn jemand auf Frage hinzufügen klickt, passiert nichts.

Getestet im Trainingsystem mit Firefox (Version 51.0.1 (32-bit)) und Chrome (Version 55.0).

**Comment by alendit** [comment]
Fixed in the newest version, I'll close it, when I'll have updated the training system.
