### ISSUE TITLE
Layout in quiz-in-video editor

### ISSUE THREAD

**Issue by mba** [TUM-MZ/moodle_mod-quizinvideo#4]
Some icon positions have to be corrected in the editor screen.
Browser: Firefox 38

![videoeditor](https://cloud.githubusercontent.com/assets/86684/8184348/3591d20a-143e-11e5-9294-f2eee983315b.png)

**Comment by abuzakaria** [comment]
fixed in https://github.com/TUM-MZ/moodle_mod-quizinvideo/commit/73b701715bf23926ac4c7c071bbffc1887aa5143 and https://github.com/TUM-MZ/TUMtheme-sources/commit/f2e8aecade766522231a184dd55e7e9729c1b9a4
