### ISSUE TITLE
Kurse mit Quiz-in-Video können nicht gesichert werden

### ISSUE THREAD

**Issue by mba** [TUM-MZ/moodle_mod-quizinvideo#8]
Kurse, denen eine Aktivität "Quiz-in-Video" eingebunden ist, können nicht gesichert werden!
Es erscheint anstelle der ersten Sicherungsmaske eine leere Seite.
Vermutung: Es werden bestimmte Bedingungen für die Sicherung nicht erfüllt.

Getestet mit:
Win8
Firefox

**Comment by alendit** [comment]
Solved
