### ISSUE TITLE
Videos vom LRZ-Wowza werden nicht korrekt eingebunden

### ISSUE THREAD

**Issue by mba** [TUM-MZ/moodle_mod-quizinvideo#9]
Beispielvideo:
rtmp://flash5.lrz-muenchen.de:1935/tum/vhb_videos_brauer/AG_Grundlagen_Aufkl_rung.mp4

Das Video wird in einem Kurs normal angezeigt, aber in Quiz-in-Video nicht.
Getestet mit: 
Win 8
Firefox

![wowza_video_nicht_angezeigt](https://cloud.githubusercontent.com/assets/86684/10477097/d295a450-7253-11e5-884b-a77ccc02a58d.png)

**Comment by abuzakaria** [comment]
fixed in commit 7cbd33a3b81f0844fbb1bfeba0366b64d1021895
